name: Send curl request with secret

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send curl request with secret
        run: |
          # Encode the secret in base64 for Basic Auth
          AUTH_HEADER=$(echo -n "username:${{ secrets.BASE_PASSWORD }}" | base64)

          echo "This is only for debug"
          echo "${{ secrets.BASE_PASSWORD }}" | base64

          # Send the curl request with Basic Authorization header
          curl -X GET "https://example.com/data" \
            -H "Authorization: Basic $AUTH_HEADER"
