name: Simulate deploy process

on:
  workflow_dispatch:

jobs:
  do-deploy:
    runs-on: ubuntu-24.04-custom

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run deploy process
        run: |
          echo "{{ secrets.BASE_PASSWORD }}" > .dockerrc

          ./deploy.sh
